# Config file for automatic testing using github actions
#

name: Unit_Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-python:
    name: Python code verification (src)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          make set-dev
          python -m pip install scapy==2.4.5
      - name: Verify code (python w/black)
        run: |
          make format-check
      - name: Run pytests (utests/tests)
        run: | 
          make test
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Dependencies
      run: |
        sudo apt-get install cmake libffi-dev python3-dev python3-pip ethtool
        sudo pip3 install setuptools nose2 scapy

        bash CI/travis/install-nanomsg.sh
        sudo ldconfig
        bash CI/travis/install-nnpy.sh

    - name: Install
      run: |
        sudo python setup.py install

    - name: Before_script
      run: |
        cd ptf_nn/; sudo ./veth_setup.sh; cd ..

    - name: Script
      run: |
        python CI/travis/check-nnpy.py
        ./CI/travis/run_tests.sh
        sudo python /usr/local/bin/nose2 utests.tests.test
