# Config file for automatic testing using github actions
#

name: Unit_Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-python:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
      # Don't abort other runs when one of them fails, to ease debugging.
      fail-fast: false

    name: Python code verification (src)
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          make set-dev
          python -m pip install scapy==2.5.0
      - name: Verify code (python w/black)
        run: |
          make format-check
      - name: Run pytests (utests/tests)
        run: | 
          make test
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
      # Don't abort other runs when one of them fails, to ease debugging.
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
        sudo apt-get install cmake libffi-dev ethtool python3-dev
        python3 -m pip install --upgrade setuptools nose2 wheel
        python -m pip install scapy==2.5.0

        bash CI/install-nanomsg.sh
        sudo ldconfig
        bash CI/install-nnpy.sh

    - name: Install
      run: |
        python3 -m pip install .
        ptf --version

    - name: Before_script
      run: |
        cd ptf_nn/; sudo ./veth_setup.sh; cd ..

    - name: Script
      run: |
        pip --verbose list
        python3 CI/check-nnpy.py
        ./CI/run_tests.sh
