# Config file for automatic testing using github actions
#

name: Unit_Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-python:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        scapy_version: [2.5.0, 2.6.1]
      # Don't abort other runs when one of them fails, to ease debugging.
      fail-fast: false

    name: Python code verification (src)
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          make set-dev
          python -m pip install scapy==${{ matrix.scapy_version }}
      - name: Verify code (python w/black)
        run: |
          make format-check
      - name: Run pytests (utests/tests)
        run: | 
          make test
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        scapy_version: [2.5.0, 2.6.1]
      # Don't abort other runs when one of them fails, to ease debugging.
      fail-fast: false

    name: run ptf unit tests
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
        echo "==================== sudo apt-get install cmake libffi-dev ethtool python3-dev python3-venv"
        sudo apt-get install cmake libffi-dev ethtool python3-dev python3-venv
        echo "==================== python3 -m venv $HOME/ptf-test-venv"
        python3 -m venv $HOME/ptf-test-venv
        source $HOME/ptf-test-venv/bin/activate
        echo "==================== python3 -m pip install --upgrade pip setuptools nose2 wheel"
        python3 -m pip install --upgrade pip setuptools nose2 wheel
        echo "==================== pip list --verbose"
        pip list --verbose
        echo "==================== python -m pip install scapy==${{ matrix.scapy_version }}"
        python -m pip install scapy==${{ matrix.scapy_version }}
        echo "==================== bash CI/install-nanomsg.sh"

        bash CI/install-nanomsg.sh
        echo "==================== pip list --verbose"
        pip list --verbose
        echo "==================== sudo ldconfig"
        sudo ldconfig
        echo "==================== bash CI/install-nnpy.sh"
        bash CI/install-nnpy.sh
        echo "==================== pip list --verbose"
        pip list --verbose

    - name: Install
      run: |
        echo "==================== pip list --verbose"
        pip list --verbose
        echo "==================== python3 -m pip install ."
        python3 -m pip install .
        echo "==================== pip list --verbose"
        pip list --verbose
        echo "==================== ptf --version"
        ptf --version

    - name: Before_script
      run: |
        cd ptf_nn/; sudo ./veth_setup.sh; cd ..

    - name: Script
      run: |
        pip --verbose list
        python3 CI/check-nnpy.py
        ./CI/run_tests.sh
